version: '3.8'
services:
  mongo:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_USER: user
      MONGODB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
